### ISSUE TITLE
If the word is not in the dictionary, it shouldn't be marked correct or incorrect

### ISSUE THREAD

**Issue by benkasminbullock** [munnellg/SpellChecker#2]
In the while (fscanf()) loop in "evaluate", the program scans the dictionary for the word using "if (strrchr (query, ":"))", then it marks the word as unknown if not:

```
                       if ( best_match( dict, target, result, BUF_MAX ) != 1 ) {
                                unknown++;
                        }
````
However, even if it is unknown, it still continues with the succeeding part of the line, in other words there is nothing to mark that we're looking for an unknown word after the `} else {` statement, so even though the word can't be found in our dictionary, we still calculate `correct` and `querycnt` as if the word could be found. This skews the final result of the program quite a lot if the dictionary doesn't contain many of the words. Using the /usr/share/dict/words given by the FreeBSD operating system, I went from 40% accuracy to 46% accuracy by rejecting lines where the word was not found in the dictionary.

**Comment by benkasminbullock** [comment]
Another thing which can happen with your method is that the spelling mistake may be something which is already in the dictionary. For example from the birkbeck file, "dong" should turn into "done", but since "done" is already in the dictionary I'm using, mentioned above, your method doesn't try to change it but leaves it as-is. This isn't a problem with your method but it seems to skew the final statistics slightly.

**Comment by munnellg** [comment]
On the first point, absolutely! If the goal is to evaluate the effectiveness of this method for retrieving a correct spelling from a pool of terms then words which are not part of the pool should be given some form of special consideration. I have updated the project to produce two sets of numbers based on whether or not we consider terms that are in the dictionary.

On the second point there really isn't an awful lot you can do for this kind of evaluation. Without any surrounding context, there is no way of knowing that "dong" is a misspelling when the dictionary you use says otherwise. Similarly if I give you the erroneous spelling "Brt" there is know way to know if I meant to write "Bart" or "Brat" without looking at the context around it. Perhaps you could use some some sort of probability prior in the latter case? Brat is possibly a more popular word than Bart, so if they are both equally good candidates then choose the more popular word.

Obviously a much smarter spell checker than this one could look at the words surrounding a typo and use some form of language model in combination with string similarity to assess the most suitable correction.

However, it is probably worth being aware of the fact that some misspellings are actually in the dictionary. I've added some code to report the number of cases where this is so.
